version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"


  - package-ecosystem: "npm"
    directory: "vre-panel"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "vreapis"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[docker] "


  - package-ecosystem: "docker"
    directory: "vre-panel"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[docker] "


  - package-ecosystem: "docker"
    directory: "tilt/vre-panel"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[docker] " (no colon, but a trailing whitespace)
      prefix: "[docker] "


  - package-ecosystem: "docker"
    directory: "tilt/vreapis"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[docker] " (no colon, but a trailing whitespace)
      prefix: "[docker] "