version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[actions] "

  - package-ecosystem: "pip"
    directory: "vreapis"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[pip] "
    groups:
      vreapis-pip:
        patterns:
          - '*'

  - package-ecosystem: "npm"
    directory: "vre-panel"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[npm] "
    groups:
      vre-panel-npm:
        patterns:
          - '*'

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[docker] "
    groups:
      vreapis-docker:
        patterns:
          - 'python'
      vre-panel-docker:
        patterns:
          - 'node'
