# Generated by Django 4.0.5 on 2022-06-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyCloakAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('issuer', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('realm_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'KeyCloak Auth',
            },
        ),
        migrations.CreateModel(
            name='SDIAProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Topology',
                'verbose_name_plural': 'Topologies',
            },
        ),
        migrations.CreateModel(
            name='AsgProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('display_name', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Asg Profile',
                'verbose_name_plural': 'Asg Profiles',
            },
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('master', 'Master'), ('worker', 'Worker')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('assign_public_ip', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('disk_size', models.CharField(max_length=5)),
                ('mem_size', models.CharField(max_length=5)),
                ('num_cores', models.IntegerField(default=2)),
                ('user_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Virtual Machine',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('profiles', models.ManyToManyField(to='assignments.AsgProfile')),
                ('provision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignments.sdiaprovision')),
            ],
            options={
                'verbose_name': 'Assignment',
            },
        ),
        migrations.AddField(
            model_name='sdiaprovision',
            name='topology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignments.topology'),
        ),
        migrations.AddField(
            model_name='sdiaprovision',
            name='vms',
            field=models.ManyToManyField(to='assignments.vm'),
        ),
    ]
