# Generated by Django 4.0.5 on 2022-06-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_sdiaprovision_options_sdiaprovision_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='provision',
        ),
        migrations.AddField(
            model_name='assignments',
            name='base_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='fqdn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='image_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='image_tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='ingress_ssl_port',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='TokenCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('gh', 'Github Repository'), ('we', 'Workflow Engine')], max_length=2, null=True)),
                ('url', models.URLField(null=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('ass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assignments.assignment')),
            ],
        ),
    ]
