# Generated by Django 4.0.10 on 2023-06-01 13:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0001_initial'),
        ('virtual_labs', '0004_remove_virtuallab_profiles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('data_url', models.URLField(null=True)),
                ('vlab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='virtual_labs.virtuallab')),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='GeoDataProduct',
            fields=[
                ('dataproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_products.dataproduct')),
                ('spatial_coverage', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('raster_data_url', models.URLField(null=True)),
            ],
            bases=('data_products.dataproduct', models.Model),
        ),
    ]
