# Generated by Django 4.2.7 on 2023-11-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
        ('data_products', '0002_alter_dataproduct_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproduct',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflow'),
        ),
    ]
