# Generated by Django 4.0.5 on 2022-06-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('virtual_labs', '0004_remove_virtuallab_profiles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('vlab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='virtual_labs.virtuallab')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('container_image', models.CharField(max_length=100, null=True)),
                ('registry_url', models.URLField(null=True)),
                ('repository_url', models.URLField(null=True)),
                ('cell_metadata', models.JSONField(null=True)),
                ('catalog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cells.catalog')),
            ],
        ),
    ]
