# Generated by Django 4.0.10 on 2023-08-16 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '__first__'),
        ('cells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='ass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assignments.assignment'),
        ),
    ]
