apiVersion: apps/v1
kind: Deployment
metadata:
  name: vreapi-deployment
  labels:
    app: vreapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vreapi
  template:
    metadata:
      labels:
        app: vreapi
    spec:
      containers:
        - name: vreapi
          image: qcdis/vreapi
          imagePullPolicy: Never
          ports:
          - containerPort: 8000
            protocol: TCP
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: secret-key

---

apiVersion: v1
kind: Service
metadata:
  name: vreapi-svc
  labels:
    app: vreapi-svc
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: vreapi
  type: ClusterIP

---

apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  secret-key: MW0yZ24waC1tI2o0cUAjaV56cV80anVkX2VhajVyb185OWRlaCgpKDBzKXYxbmtiKCsK