services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      - POSTGRES_DB=vrepaas
      - POSTGRES_PASSWORD=vrepaas
      - POSTGRES_USER=vrepaas

  app:
    image: vreapi
    container_name: app
    environment:
      - DB_HOST=db
      - DB_NAME=vrepaas
      - DB_PASSWORD=vrepaas
      - DB_PORT=5432
      - DB_USER=vrepaas
      - ALLOWED_HOST=*
      - ARGO_NAMESPACE=
      - ARGO_URL=
      - BASE_PATH=/vre-api-test
      - CALL_BACK_URL=
      - CORS_ALLOWED_ORIGIN_REGEXES=
      - DJANGO_SETTINGS_MODULE=vreapis.settings.development
      - DJANGO_SUPERUSER_EMAIL=admin@example.org
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_USERNAME=user
      - TRUSTED_ORIGINS=http://localhost
      - ARGO_API_TOKEN=
      - DJANGO_PASSWORD=user
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_TOKEN=token
      - SECRET_KEY=secret
      - CELL_GITHUB=https://github.com/QCDIS/NaaVRE-cells-test-3
      - CELL_GITHUB_TOKEN=${CELL_GITHUB_TOKEN}
    ports:
      - '127.0.0.1:8000:8000'
    healthcheck:
      test: |
        curl --fail http://localhost:8000/vre-api-test/api/
      interval: 5s
