# Generated by Django 5.0.3 on 2024-06-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('task_name', models.CharField(max_length=255)),
                ('original_source', models.CharField(max_length=255)),
                ('types', models.JSONField(blank=True, default=dict, null=True)),
                ('base_image', models.JSONField(blank=True, null=True)),
                ('inputs', models.JSONField(blank=True, default=list, null=True)),
                ('outputs', models.JSONField(blank=True, default=list, null=True)),
                ('params', models.JSONField(blank=True, default=list, null=True)),
                ('param_values', models.JSONField(blank=True, null=True)),
                ('confs', models.JSONField(blank=True, null=True)),
                ('dependencies', models.JSONField(blank=True, null=True)),
                ('chart_obj', models.JSONField(blank=True, null=True)),
                ('node_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('container_source', models.CharField(max_length=255)),
                ('global_conf', models.JSONField(blank=True, null=True)),
                ('kernel', models.CharField(max_length=255)),
                ('notebook_dict', models.JSONField(blank=True, null=True)),
                ('image_version', models.CharField(max_length=255)),
            ],
        ),
    ]
