# Generated by Django 5.0.3 on 2024-06-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='container_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='image_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
