# Generated by Django 5.0.3 on 2024-06-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_cell_container_source_alter_cell_image_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='container_source',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='image_version',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='kernel',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='cell',
            name='node_id',
            field=models.CharField(max_length=4000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cell',
            name='original_source',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='cell',
            name='task_name',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='cell',
            name='title',
            field=models.CharField(max_length=4000),
        ),
    ]
