# Generated by Django 4.0.10 on 2023-08-19 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsgProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Asg Profile',
                'verbose_name_plural': 'Asg Profiles',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('base_url', models.CharField(max_length=100, null=True)),
                ('fqdn', models.CharField(max_length=100, null=True)),
                ('ingress_ssl_port', models.CharField(max_length=5, null=True)),
                ('image_name', models.CharField(max_length=100, null=True)),
                ('image_tag', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Virtual Lab',
            },
        ),
        migrations.CreateModel(
            name='KeyCloakAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('issuer', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('realm_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'KeyCloak Auth',
            },
        ),
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Topology',
                'verbose_name_plural': 'Topologies',
            },
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('master', 'Master'), ('worker', 'Worker')], max_length=10)),
                ('display_name', models.CharField(max_length=100)),
                ('assign_public_ip', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('disk_size', models.CharField(max_length=5)),
                ('mem_size', models.CharField(max_length=5)),
                ('num_cores', models.IntegerField(default=2)),
                ('user_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Virtual Machine',
            },
        ),
        migrations.CreateModel(
            name='TokenCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('gh', 'Github Repository'), ('we', 'Workflow Engine')], max_length=2, null=True)),
                ('url', models.URLField(null=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('Asgab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assignments.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='SDIAProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('topology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignments.topology')),
                ('vms', models.ManyToManyField(to='assignments.vm')),
            ],
            options={
                'verbose_name': 'SDIA Provision',
            },
        ),
    ]
