# Generated by Django 4.0.10 on 2023-08-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Assignment'},
        ),
        migrations.DeleteModel(
            name='SDIAProvision',
        ),
        migrations.DeleteModel(
            name='Topology',
        ),
        migrations.DeleteModel(
            name='VM',
        ),
       
    ]
