# Generated by Django 4.0.5 on 2022-06-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlprofile',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
    ]
