# Generated by Django 4.0.10 on 2023-08-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='display_name',
        ),
    ]
