# Generated by Django 4.0.10 on 2023-08-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_remove_assignment_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='display_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
