# Generated by Django 4.0.10 on 2023-08-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asgprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='image_tag',
        ),
    ]
