# Generated by Django 4.0.10 on 2023-08-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_remove_asgprofile_image_remove_assignment_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='vlab_slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
