# Generated by Django 4.0.10 on 2023-08-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_assignment_vlab_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='long_description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
