# Generated by Django 4.0.10 on 2023-09-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_rename_description_assignment_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='vlab_slug',
        ),
    ]
