# Generated by Django 4.0.10 on 2023-09-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_keycloak_id'),
        ('assignments', '0009_remove_assignment_vlab_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='enrolled_studebts',
            field=models.ManyToManyField(null=True, to='students.student'),
        ),
    ]
