# Generated by Django 4.0.10 on 2023-09-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_keycloak_id'),
        ('assignments', '0010_assignment_enrolled_studebts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='enrolled_studebts',
            field=models.ManyToManyField(blank=True, null=True, to='students.student'),
        ),
    ]
