# Generated by Django 4.0.10 on 2023-09-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_alter_assignment_enrolled_studebts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='enrolled_studebts',
            new_name='enrolled_students',
        ),
    ]
