# Generated by Django 4.0.10 on 2023-09-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0013_file_assignment_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='files',
        ),
        migrations.AddField(
            model_name='assignment',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='assignments.file'),
        ),
    ]
