# Generated by Django 4.0.10 on 2023-09-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0015_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='isEnrolled',
            field=models.BooleanField(default=False),
        ),
    ]
