# Generated by Django 4.0.10 on 2023-09-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0016_assignment_isenrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='isEnrolled',
        ),
    ]
