# Generated by Django 4.0.10 on 2023-10-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_labs', '0004_remove_virtuallab_profiles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualLabInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('vlab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_labs.virtuallab')),
            ],
        ),
    ]
