# Generated by Django 4.0.10 on 2023-09-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
