# Generated by Django 4.0.10 on 2023-09-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assignments_enrolled',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
