# Generated by Django 4.0.10 on 2023-09-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_assignments_enrolled_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='keycloak_ID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
