# Generated by Django 4.0.10 on 2023-09-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_keycloak_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='assignments_enrolled',
        ),
        migrations.AddField(
            model_name='student',
            name='assignments_enrolled',
            field=models.ManyToManyField(blank=True, null=True, to='students.student'),
        ),
    ]
