# Generated by Django 4.0.10 on 2023-09-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_assignments_enrolled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='assignments_enrolled',
        ),
        migrations.AddField(
            model_name='student',
            name='assignments_enrolled',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
