# Generated by Django 4.0.10 on 2023-09-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_student_assignments_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assignments_enrolled',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
