name: Build container

on:
  workflow_call:
    inputs:
      docker_folder:
        required: true
        type: string
      tag:
        required: true
        type: string
      push:
        required: true
        type: boolean
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true
env:
  DOCKER_FOLDER:  ${{ inputs.docker_folder }}
  TAG:  ${{ inputs.tag }}
  DOCKERHUB_IMAGE_ID: "qcdis/"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker
      run: |
          cd $DOCKER_FOLDER && docker build . --file Dockerfile -t $TAG

    - name: Login to github Registry
      if: ${{ inputs.push }}
      uses: docker/login-action@v2
      with:
        registry: "https://index.docker.io/v1/"
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
    - name: Push image to container Registry
      if: ${{ inputs.push }}
      run: |
        # Change all uppercase to lowercase
        IMAGE_ID=$DOCKERHUB_IMAGE_ID$TAG
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $TAG $IMAGE_ID:$VERSION        
        if [ "${{ secrets.docker_password }}" != '' ]; then
          docker push $IMAGE_ID:$VERSION
          docker tag $TAG $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
        fi