name: make
on:
  push:
  schedule:
    - cron: '0 4 5,25 * *'

jobs:
  call-build-container-vreapis:
    uses: ./.github/workflows/build-container.yml
    with:
      docker_folder: vreapis
      tag: vreapi
      push: false
    secrets:
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  call-build-container-vre-panel:
    uses: ./.github/workflows/build-container.yml
    strategy:
      matrix:
        environment:
          - production
          - test
    with:
      docker_folder: vre-panel
      tag: vreapp
      environment: ${{ matrix.environment }}
      push: false
    secrets:
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
